---
- name: Copy project files 
  synchronize:
    src: ../../../../../backend/
    dest: /app
    delete: yes
    rsync_opts:
      - "--exclude=.env"

- name: Create .env file
  copy:
    content: |
      DB_PASSWORD={{ DB_password }}
      DB_USER={{ DB_user }}
      DB_NAME={{ DB_name }}
      DB_HOST={{ DB_host }}
      JWT_SECRET={{ JWT_secret }}
    dest: /app/.env
    owner: root
    group: root
    mode: '0644'

- name: Build Docker image
  docker_image:
    name: backend
    build:
      path: /app
    source: build
    state: present

- name: Run Docker container
  docker_container:
    name: backend
    image: backend
    state: started
    ports:
      - "8081:8081"
    detach: true