---
- name: Copy necessary project files
  synchronize:
    src: ../../../../../admin-panel/
    dest: /app
    rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=build"
          - "--exclude=.env"

- name: Create .env file for frontend
  copy:
    content: |
      REACT_APP_API_URL={{ REACT_APP_API_URL }}
    dest: /app/.env
    owner: root
    group: root
    mode: '0644'

- name: Build Docker image for frontend
  command: docker build -t front-adm /app

- name: Run Docker container for frontend
  docker_container:
    name: front-adm
    image: front-adm
    state: started
    ports:
      - "80:80"
    detach: true