---
- hosts: all
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - role: postgresql
      vars:
        DB_user: "{{ db_user }}"
        DB_password: "{{ db_password }}"
        DB_name: "{{ db_name }}"
      when: inventory_hostname == 'ling-db'