name: Admin Panel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --prefix admin-panel

    - name: Build
      run: npm run build --prefix admin-panel

    #- name: Run tests
    #  run: npm test --prefix admin-panel
